{
 "title": "pg_stat_statements",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "region", "query": "us-east-1" }
  ]
 },
 "panels": [
  {
   "title": "Top 50 mean-time longest running queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms", "label": "mean exec time" }
   ],
   "targets": [
    {
     "rawSql": "select (ROW_NUMBER() OVER (ORDER BY MAX(mean_time) desc)+$__unixEpochFrom()) as time, \nmd5(query) as metric, MAX(mean_time)\nfrom statement_stats where query <> 'DISCARD ALL' AND statdate = (SELECT statdate from\nstatement_stats order by statdate desc limit 1) group by query order by time LIMIT 50;",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Top 50 most called sql statements",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "locale", "label": "# of statement calls" }
   ],
   "targets": [
    {
     "rawSql": "select (ROW_NUMBER() OVER (ORDER BY MAX(calls))+$__unixEpochFrom()) as time, \nmd5(query) as metric,MAX(calls)\nfrom statement_stats where query <> 'DISCARD ALL' AND statdate = (SELECT statdate from\nstatement_stats order by statdate desc limit 1) group by query order by time desc LIMIT 50; ",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Latest Query Stats",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "select md5(query) as md5, left(query,100) as statement, MAX(calls) as maxcalls, MIN(min_time) as mintime, MAX(mean_time) as meantime, MAX(max_time) as maxtime from statement_stats where query <> 'DISCARD ALL' AND statdate = (SELECT statdate from statement_stats order by statdate desc limit 1) group by query order by maxcalls desc",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}